language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"

before_script:
  - composer self-update
  - composer install --prefer-dist
  - php -S localhost:8080 ./web/index.php &
  - sleep 3

script:
  - ./bin/phpspec run
  - ./bin/behat --config ./behat.yml --profile travis
#  - phpunit --coverage-clover=coverage.clover
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
